name:                custom-login
version:             0.1.0.0
github:              "freizl/haskell-okta"
license:             Apache-2.0
author:              Haisheng Wu
maintainer:          freizl@gmail.com
copyright:           Haisheng Wu
category:            Web
build-type:          Simple

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/freizl/haskell-oktacustom-login>

dependencies:
- base >= 4.7 && < 5

executables:
  custom-login-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    dependencies:
    - lens
    - unordered-containers
    - scotty
    - okta-samples-common

tests:
  custom-login-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-types
    - bytestring
    - text
    - lens
    - jose
    - aeson
    - process
    - wai-extra
    - tasty
    - tasty-hspec
    - tasty-ant-xml
    - hspec
    - hspec-wai
    - wai
