language: haskell

notifications:
  slack: freizl:D42Dy68Q4Cj8Bjw5Qi9mZrQf

cache:
  directories:
    - $HOME/.cabal
    - ./dist-newstyle

cabal: "2.4"

ghc:
  - "8.6.5"

env:
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=build

script:
  - make $TEST_SUITE

install:
  - cabal v2-install
  - cabal v2-install hlint
