name:                buildtool
version:             0.1.0.0
github:              "freizl/haskell-okta"
license:             Apache-2.0
author:              Haisheng Wu
maintainer:          freizl@gmail.com
copyright:           Haisheng Wu
category:            Web
build-type:          Simple

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/freizl/haskell-okta/buildtool>

dependencies:
- base >= 4.7 && < 5


executables:
  buildtool:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - turtle
    - text
