{-# LANGUAGE OverloadedStrings #-}

module AppCustomLogin (app, waiApp) where

import           Prelude                   hiding (exp)
import           Web.Scotty

import           Okta.Samples.Common.Types
import           Okta.Samples.Common.Utils
import qualified Web.Scotty.Okta.App       as Okta
import           Web.Scotty.Okta.Handlers
import           Web.Scotty.Okta.Sessions


------------------------------
-- App
------------------------------

app :: AppOption -> IO ()
app opt = do
  cf <- readConfigFile
  case cf of
    Left l  -> print l
    Right c -> Okta.runApp c (waiApp opt c)

waiApp opt c = Okta.waiApp opt $ do
  get "/login" $ loginCustomH c
  get "/authorization-code/callback" $ callbackH c
  get "/" homeH
  get "/profile" $ profileH c
  get "/logout" logoutH
--------------------------------------------------
-- * Handlers
--------------------------------------------------

callbackH :: Config -> ActionM ()
callbackH c = do
  -- params from cookie which is generated by okta-signin-widget
  stateC <- getCookiesM "okta-oauth-state"
  nonceC <- getCookiesM "okta-oauth-nonce"
  authorizeCallbackH c stateC nonceC
