{-# LANGUAGE OverloadedStrings #-}

module AppCustomLogin (app, waiApp) where

import qualified Network.Wai               as WAI
import           Prelude                   hiding (exp)
import           Web.Scotty

import           Okta.Samples.Common.OIDC
import           Okta.Samples.Common.Types
import           Okta.Samples.Common.Utils
import qualified Web.Scotty.Okta.App       as Okta
import           Web.Scotty.Okta.Handlers
import           Web.Scotty.Okta.Sessions


------------------------------
-- App
------------------------------

app :: AppOption -> IO ()
app opt = do
  cf <- readConfigFile
  case cf of
    Left l  -> print l
    Right c -> Okta.runApp c (waiApp opt c)

waiApp :: AppOption -> Config -> OpenIDConfiguration -> IO WAI.Application
waiApp opt c oc = Okta.waiApp opt $ do
  get "/login" $ loginCustomH c
  get "/authorization-code/callback" $ callbackH c oc
  get "/" homeH
  get "/profile" $ profileH c
  get "/logout" logoutH
--------------------------------------------------
-- * Handlers
--------------------------------------------------

callbackH :: Config -> OpenIDConfiguration -> ActionM ()
callbackH c oc = do
  -- params from cookie which is generated by okta-signin-widget
  stateC <- getCookiesM "okta-oauth-state"
  nonceC <- getCookiesM "okta-oauth-nonce"
  authorizeCallbackH c oc stateC nonceC
