app=cabal v2-exec login-with-okta-exe --

run-help:
	$(app) --help

run-preview-freizl:
	$(app) -i https://dev-148986.oktapreview.com -c 0oad3popatwUIhWV40h7 -x YFqXRjtsy7IYRbueiG2tcgHzhaawLccxqq5ruPfN
run-preview-freizl-cas:
	$(app) -i https://dev-148986.oktapreview.com -c 0oad3popatwUIhWV40h7 -x YFqXRjtsy7IYRbueiG2tcgHzhaawLccxqq5ruPfN --custom-as default


run-rain:
	$(app) -i https://rain.okta1.com -c 0oat5oPa8vbvONsyr0g3 -x d3sa7boI_oJC4688IDQ2kwwEeI7QKplTQaQX_XxY
run-rain-cas:
	$(app) -i https://rain.okta1.com -c 0oat5oPa8vbvONsyr0g3 -x d3sa7boI_oJC4688IDQ2kwwEeI7QKplTQaQX_XxY --custom-as default


run-ct7-oie:
	$(app) -i https://ct7-oie.clouditude.com -c 0oa2z0q0PBv2KBpNP344 -x RqDwetmtj6U88Qr-40lHgQoIyIX2MWufTbY5B63D
run-ct7-oie-cas:
	$(app) -i https://ct7-oie.clouditude.com -c 0oa2z0q0PBv2KBpNP344 -x RqDwetmtj6U88Qr-40lHgQoIyIX2MWufTbY5B63D --custom-as default


run-tc-hw-oie:
	$(app) -i https://hw-oie.trexcloud.com -c 0oa2w9slo9xUbSPrt0g7 -x T63Z3BHiAqbQHie7KggpsUPm8PiMvWZTLOScCG6H
run-tc-hw-oie-cas:
	$(app) -i https://hw-oie.trexcloud.com -c 0oa2w9slo9xUbSPrt0g7 -x T63Z3BHiAqbQHie7KggpsUPm8PiMvWZTLOScCG6H --custom-as default
