name:                login-with-okta
version:             0.2.0.0
github:              "freizl/haskell-okta"
license:             Apache-2.0
author:              Haisheng Wu
maintainer:          freizl@gmail.com
copyright:           Haisheng Wu
category:            Web
build-type:          Simple

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/freizl/haskell-okta/okta-hosted-login>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:
    - src
  ghc-options:
    - -Wall
  dependencies:
    - lens
    - unordered-containers
    - scotty
    - text
    - optparse-applicative
    - aeson
    - aeson-pretty
    - jose
    - monad-time
    - network-uri
    - bytestring
    - http-conduit
    - http-types
    - cookie
    - binary
    - wai
    - wai-extra
    - wai-middleware-static
    - warp
    - time
    - mtl
    - lucid

executables:
  login-with-okta-exe:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - login-with-okta
    - optparse-applicative

tests:
  login-with-okta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - login-with-okta
    - http-types
    - bytestring
    - text
    - lens
    - jose
    - aeson
    - process
    - wai-extra
    - tasty
    - tasty-hspec
    - tasty-ant-xml
    - hspec
    - hspec-wai
    - wai
    - lucid
