name:                okta-samples-unit-test
version:             0.1.0.0
github:              "freizl/samples-common"
license:             BSD3
author:              "Haisheng Wu"
maintainer:          "freizl@gmail.com"
copyright:           "2016 Haisheng Wu"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/freizl/samples-common#readme>

dependencies:
- base >= 4.7 && < 5

tests:
  okta-samples-unit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okta-hosted-login
    - custom-login
    - okta-samples-common
    - http-types
    - bytestring
    - text
    - lens
    - jose
    - aeson
    - process
    - wai-extra
    - tasty
    - tasty-hspec
    - tasty-ant-xml
    - hspec
    - hspec-wai
    - wai
    - lucid
